
gems_dir = File.dirname( __FILE__ )
target_dir = gems_dir + '/../target'
target_gems_dir = target_dir + '/gems'

require 'fileutils'
require 'rubygems'
require 'hoe'

if ( ENV['FULL_BUILD'] == nil ) 
  task :default do
    puts "intentionally building nothing"
  end
else
  task :default=>[:build_and_install_gems] do
    # nothing
  end
end


task :build_and_install_gems=>[ :build_gems, :install_gems ] do
  # nothing
end

task :build_gems=>[ :prepare_target ] do
  gem_dir = gems_dir + "/activerecord-jdbc-adapter"

  Dir.chdir( gem_dir ) do 
    `rake all:package`
  end
end

task :install_gems do 
  gem_dir = gems_dir + "/activerecord-jdbc-adapter"

  Dir.chdir( gem_dir ) do 
    gems = Dir[ "pkg/*.gem" ] + Dir[ "drivers/*/pkg/*.gem" ] + Dir[ "adapters/*/pkg/*.gem" ] 
    puts `GEM_PATH=#{target_gems_dir} gem install -f -i #{target_gems_dir} --local --no-ri --no-rdoc #{gems.join(' ' )}`
  end
end

task :prepare_target do
  FileUtils.mkdir_p( target_gems_dir )
end

task :clean do
  Dir.chdir( gems_dir + '/activerecord-jdbc-adapter' ) { `rake all:clean` }
end

task :prepare_gems=>[ :activerecord_jdbc_adapter ] do
end
